function draw(){ctx.clearRect(0,0,W,H);const gr=ctx.createLinearGradient(0,0,0,H);gr.addColorStop(0,'#174b3e');gr.addColorStop(1,'#08271f');ctx.fillStyle=gr;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.045;ctx.strokeStyle='#fff';for(let x=-H;x<W+H;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x-H,H);ctx.stroke()}ctx.globalAlpha=1;
for(let m=0;m<worldH;m+=400){const y=sy(m);if(y<-30||y>H+30)continue;ctx.fillStyle='rgba(255,255,255,.045)';ctx.fillRect(0,y,W,1);ctx.fillStyle='rgba(255,255,255,.26)';ctx.font='800 9px system-ui';ctx.textAlign='left';ctx.fillText(`${Math.round(m/worldH*100)}%`,14,y-6)}
for(const mk of courseMarks){const y=sy(mk.y);if(y<-20||y>H+20)continue;ctx.fillStyle='rgba(255,255,255,.11)';rr(ctx,12,y-12,Math.min(190,W*.28),24,8);ctx.fill();ctx.fillStyle='rgba(255,255,255,.68)';ctx.font='900 9px system-ui';ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillText(mk.label,22,y)}
if(cameraY<85){ctx.fillStyle='rgba(255,255,255,.06)';rr(ctx,15,13,W-30,52,14);ctx.fill();ctx.fillStyle='rgba(255,255,255,.8)';ctx.font='900 12px system-ui';ctx.textAlign='left';ctx.fillText('DROP ZONE',29,44);ctx.textAlign='right';ctx.fillStyle='rgba(182,223,102,.95)';ctx.fillText('SB365 LONG ARENA',W-29,44)}
for(const s of rails){const y1=sy(s.y1),y2=sy(s.y2);if(Math.max(y1,y2)<-40||Math.min(y1,y2)>H+40)continue;ctx.save();ctx.translate(0,-cameraY);drawRail(s);ctx.restore()}
for(const p of pegs){const y=sy(p.y);if(y<-20||y>H+20)continue;const pg=ctx.createRadialGradient(p.x-2,y-3,1,p.x,y,p.r+3);pg.addColorStop(0,'#e2fff0');pg.addColorStop(.55,'#73d6ad');pg.addColorStop(1,'#1f8261');ctx.fillStyle=pg;ctx.beginPath();ctx.arc(p.x,y,p.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.22)';ctx.stroke()}
for(const sp of spinners){const sg=spinnerSegment(sp);if(Math.max(sy(sg.y1),sy(sg.y2))<-40||Math.min(sy(sg.y1),sy(sg.y2))>H+40)continue;ctx.strokeStyle='rgba(240,130,189,.95)';ctx.lineWidth=sp.w;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(sg.x1,sy(sg.y1));ctx.lineTo(sg.x2,sy(sg.y2));ctx.stroke();ctx.fillStyle='#ffd8eb';ctx.beginPath();ctx.arc(sp.x,sy(sp.y),10,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(240,130,189,.85)';ctx.lineWidth=3;ctx.stroke()}
for(const r of rotors){const y=sy(r.y);if(y<-r.r-30||y>H+r.r+30)continue;ctx.save();ctx.translate(r.x,y);ctx.fillStyle='rgba(40,101,88,.98)';ctx.strokeStyle='rgba(118,223,184,.98)';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,r.r,0,Math.PI*2);ctx.fill();ctx.stroke();if(r.hit>0){ctx.globalAlpha=Math.min(1,r.hit);ctx.strokeStyle='rgba(215,255,236,.95)';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,r.r+14*(1-r.hit),0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}ctx.fillStyle='rgba(215,255,236,.32)';ctx.beginPath();ctx.arc(0,0,r.r*.36,0,Math.PI*2);ctx.fill();ctx.restore()}
for(const gate of gates){const gy=sy(gate.y);if(gy<-40||gy>H+40)continue;for(const sg of gateSegments(gate)){ctx.save();ctx.translate(0,-cameraY);drawRail(sg);ctx.restore()}const half=gate.gapW/2;ctx.fillStyle='rgba(255,224,119,.9)';ctx.font='900 9px system-ui';ctx.textAlign='center';ctx.textBaseline='bottom';ctx.fillText('OPEN',gate.gapX,gy-10);ctx.strokeStyle='rgba(255,224,119,.55)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(gate.gapX-half,gy-4);ctx.lineTo(gate.gapX+half,gy-4);ctx.stroke()}
for(const f of flippers){const sg=flipperSegment(f);if(Math.max(sy(sg.y1),sy(sg.y2))<-40||Math.min(sy(sg.y1),sy(sg.y2))>H+40)continue;ctx.strokeStyle='rgba(255,151,191,.97)';ctx.lineWidth=f.w;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(sg.x1,sy(sg.y1));ctx.lineTo(sg.x2,sy(sg.y2));ctx.stroke();ctx.fillStyle='#ffe0ec';ctx.beginPath();ctx.arc(f.x,sy(f.y),10,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,151,191,.9)';ctx.lineWidth=3;ctx.stroke()}
const fy=sy(finishY);if(fy>-80&&fy<H+80){ctx.fillStyle='rgba(255,255,255,.075)';ctx.fillRect(0,fy,W,80);const seg=14,sw=W/seg;for(let i=0;i<seg;i++){ctx.fillStyle=i%2?'rgba(255,255,255,.72)':'rgba(182,223,102,.94)';ctx.fillRect(i*sw,fy,sw,8)}ctx.fillStyle='rgba(255,255,255,.8)';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillText('FINISH',W/2,fy+32)}
for(const b of balls){if(trail)for(const t of b.tr){const ty=sy(t.y);if(ty<-20||ty>H+20)continue;ctx.globalAlpha=t.a*.16;ctx.fillStyle=b.c;ctx.beginPath();ctx.arc(t.x,ty,b.r*.82,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(b.done)continue;const y=sy(b.y);if(y<-30||y>H+30)continue;ctx.shadowColor='rgba(0,0,0,.3)';ctx.shadowBlur=9;ctx.shadowOffsetY=3;ctx.fillStyle=b.c;ctx.beginPath();ctx.arc(b.x,y,b.r,0,Math.PI*2);ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='rgba(255,255,255,.78)';ctx.lineWidth=1.2;ctx.stroke();if(b.r>=8.5){ctx.fillStyle=ballTextColor(b.c);ctx.font=`900 ${Math.max(5.8,Math.min(7.5,b.r*.58))}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.name,b.x,y+.5,b.r*1.72)}if(b.waiting&&balls.length<=14){ctx.fillStyle='rgba(255,255,255,.9)';ctx.font='800 10px system-ui';ctx.textAlign='center';ctx.textBaseline='top';ctx.fillText(b.name,b.x,y+b.r+6)}}
for(const q of conf){const y=sy(q.y);ctx.save();ctx.globalAlpha=Math.max(0,q.a);ctx.translate(q.x,y);ctx.rotate(q.rot);ctx.fillStyle=q.c;ctx.fillRect(-q.s/2,-q.s/2,q.s,q.s*1.8);ctx.restore()}
if(!run&&!balls.length){ctx.fillStyle='rgba(255,255,255,.78)';ctx.font='950 25px system-ui';ctx.textAlign='center';ctx.fillText('READY',W/2,H*.43);ctx.fillStyle='rgba(255,255,255,.4)';ctx.font='500 12px system-ui';ctx.fillText('긴 코스 · 미니맵 · 다양한 장애물',W/2,H*.43+27);ctx.fillText('START를 누르면 카메라가 구슬을 따라 내려갑니다',W/2,H*.43+48)}drawMini()}
function drawMini(){const mw=130,mh=260;mctx.clearRect(0,0,mw,mh);mctx.fillStyle='#092b23';mctx.fillRect(0,0,mw,mh);const sx=mw/W,syc=mh/worldH;
 mctx.globalAlpha=.42;for(const s of rails){mctx.strokeStyle=s.type==='split'?'#f8be5c':s.type==='slot'?'#76cdff':s.type==='final'?'#ff8eb1':s.type==='stair'?'#ae97ff':'#84a8ff';mctx.lineWidth=1.15;mctx.beginPath();mctx.moveTo(s.x1*sx,s.y1*syc);mctx.lineTo(s.x2*sx,s.y2*syc);mctx.stroke()}for(const sp of spinners){mctx.fillStyle='#f082bd';mctx.fillRect(sp.x*sx-2,sp.y*syc-1,4,2)}for(const r of rotors){mctx.strokeStyle='#76dfb8';mctx.lineWidth=1.2;mctx.beginPath();mctx.arc(r.x*sx,r.y*syc,Math.max(2,r.r*sx),0,Math.PI*2);mctx.stroke()}for(const g of gates){mctx.strokeStyle='#ffd777';mctx.lineWidth=1.2;for(const sg of gateSegments(g)){mctx.beginPath();mctx.moveTo(sg.x1*sx,sg.y1*syc);mctx.lineTo(sg.x2*sx,sg.y2*syc);mctx.stroke()}}for(const f of flippers){const sg=flipperSegment(f);mctx.strokeStyle='#ff97bf';mctx.lineWidth=1.2;mctx.beginPath();mctx.moveTo(sg.x1*sx,sg.y1*syc);mctx.lineTo(sg.x2*sx,sg.y2*syc);mctx.stroke()}mctx.globalAlpha=1;
 for(const b of balls){if(b.done)continue;mctx.fillStyle=b.c;mctx.beginPath();mctx.arc(b.x*sx,b.y*syc,2.4,0,Math.PI*2);mctx.fill()}mctx.strokeStyle='rgba(255,255,255,.95)';mctx.lineWidth=1.4;mctx.strokeRect(1,cameraY*syc+1,mw-2,Math.max(8,H*syc-2));mctx.fillStyle='rgba(182,223,102,.9)';mctx.fillRect(0,finishY*syc,mw,2)}
