function aimMini(e){const r=mini.getBoundingClientRect(),y=clamp(e.clientY-r.top,0,r.height),worldY=(y/r.height)*worldH;cameraY=clamp(worldY-H/2,0,worldH-H);draw()}
mini.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;manualCameraHeld=true;manualPointerId=e.pointerId;mini.setPointerCapture?.(e.pointerId);aimMini(e);e.preventDefault()});
mini.addEventListener('pointermove',e=>{if(!manualCameraHeld||e.pointerId!==manualPointerId)return;aimMini(e);e.preventDefault()});
function releaseMini(e){if(!manualCameraHeld)return;if(e&&manualPointerId!==null&&e.pointerId!==manualPointerId)return;manualCameraHeld=false;if(e&&mini.hasPointerCapture?.(e.pointerId))mini.releasePointerCapture?.(e.pointerId);manualPointerId=null}
mini.addEventListener('pointerup',releaseMini);mini.addEventListener('pointercancel',releaseMini);mini.addEventListener('lostpointercapture',()=>{manualCameraHeld=false;manualPointerId=null});
names.addEventListener('input',()=>window.SB365Multi?.handleNames?.()??update());start.addEventListener('click',()=>window.SB365Multi?.startSelected?.()??startGame());shuffleBtn.addEventListener('click',()=>{const p=parse();if(p.out.length<2)return pop('참가자를 2명 이상 입력하세요.');prepared=mix([...p.out]);pop('구슬 순서를 섞었습니다.');beep(520,.04,.02)});
function fastOn(e){if(e.pointerType==='mouse'&&e.button!==0)return;fastForward=true;fastPointerId=e.pointerId;fastBtn.classList.add('active');fastBtn.setPointerCapture?.(e.pointerId);e.preventDefault()}
function fastOff(e){if(e&&fastPointerId!==null&&e.pointerId!==undefined&&e.pointerId!==fastPointerId)return;fastForward=false;fastBtn.classList.remove('active');if(e&&fastBtn.hasPointerCapture?.(e.pointerId))fastBtn.releasePointerCapture?.(e.pointerId);fastPointerId=null}
fastBtn.addEventListener('pointerdown',fastOn);fastBtn.addEventListener('pointerup',fastOff);fastBtn.addEventListener('pointercancel',fastOff);fastBtn.addEventListener('lostpointercapture',()=>{fastForward=false;fastPointerId=null;fastBtn.classList.remove('active')});window.addEventListener('pointerup',()=>{if(fastForward){fastForward=false;fastPointerId=null;fastBtn.classList.remove('active')}});
$('#sample').onclick=()=>{names.value='임정훈, 김희승, 이범석, 이세임, 이현우';(window.SB365Multi?.handleNames?.()??update())};$('#clear').onclick=()=>{names.value='';(window.SB365Multi?.handleNames?.()??update());names.focus()};$('#soundBtn').onclick=()=>{sound=!sound;syncToggles();save();if(sound)beep()};$('#fullBtn').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&!run&&!counting)(window.SB365Multi?.startSelected?.()??startGame())});window.addEventListener('resize',resize);document.addEventListener('fullscreenchange',()=>setTimeout(resize,80));load();resize();update();status.textContent='대기 중 · 1등 당첨';
