(() => {
  const multi=window.SB365Multi;if(!multi)return;
  const canvas=document.querySelector('#altGame'),ctx=canvas.getContext('2d');
  const tabs=[...document.querySelectorAll('.modeTab')],feed=document.querySelector('#eventFeed');
  const originalStart=multi.startSelected.bind(multi);
  let running=false,counting=false,last=0,started=0,S=null,raf=0;
  const rnd=(a,b)=>a+Math.random()*(b-a);
  function resize(){const r=board.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx.setTransform(d,0,0,d,0,0);return{w:r.width,h:r.height};}
  function lock(v){names.disabled=v;shuffleBtn.disabled=v;start.disabled=v;tabs.forEach(x=>x.disabled=v);}
  function event(t,ttl=1300){feed.innerHTML=`<span class="eventChip">${String(t).replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]))}</span>`;clearTimeout(event.t);event.t=setTimeout(()=>feed.innerHTML='',ttl);}
  function ell(r){return Math.hypot((r.x-S.cx)/S.rx,(r.y-S.cy)/S.ry);}
  function ranking(){const alive=S.racers.filter(x=>x.alive).sort((a,b)=>ell(a)-ell(b));return[...alive,...[...S.out].reverse()];}
  function updateRank(){const list=ranking();liveRankList.innerHTML='';list.slice(0,7).forEach((b,i)=>{const row=document.createElement('div');row.className='liveRankRow'+(i===0?' leader':'');const tc=ballTextColor(b.c);row.innerHTML=`<span class="liveRankNo" style="background:${b.c};color:${tc};border:1px solid rgba(255,255,255,.24)">${i+1}</span><i class="liveRankDot" style="background:${b.c}"></i><span class="liveRankName"></span>`;row.querySelector('.liveRankName').textContent=b.name;liveRankList.appendChild(row);});if(list.length>7){const m=document.createElement('div');m.className='liveRankMore';m.textContent=`+${list.length-7}명`;liveRankList.appendChild(m);}meta.textContent=`${S.out.length} / ${S.racers.length} 탈락`;results.innerHTML='';list.slice(0,8).forEach((b,i)=>{const el=document.createElement('div');el.className='result';el.innerHTML=`<span class="rank">${i+1}</span><i class="colorDot" style="background:${b.c}"></i><span class="rname"></span><span class="time"></span>`;el.querySelector('.rname').textContent=b.name;el.querySelector('.time').textContent=b.alive?'생존':'OUT';results.appendChild(el);});}
  function nearest(r){let t=null,d=1e9;for(const o of S.racers){if(o===r||!o.alive)continue;const q=Math.hypot(o.x-r.x,o.y-r.y);if(q<d){d=q;t=o;}}return{t,d};}
  function hit(t,nx,ny,f,blast=false){t.vx+=nx*f;t.vy+=ny*f;t.hit=1;if(blast)t.blast=.62;}
  function punch(r){const t=S.racers.find(x=>x.id===r.target&&x.alive);r.target=null;if(!t)return;const dx=t.x-r.x,dy=t.y-r.y,d=Math.hypot(dx,dy)||1;if(d>160)return;const nx=dx/d,ny=dy/d,f=(S.sudden?300:225)+Math.random()*(S.sudden?70:60);hit(t,nx,ny,f);r.vx-=nx*28;r.vy-=ny*28;r.flash=1;S.fx.push({type:'pow',x:r.x+nx*Math.min(55,d*.7),y:r.y+ny*Math.min(55,d*.7),age:0,ttl:.55,text:'POW!'});event(`🥊 ${r.name} → ${t.name} 펀치!`);beep(240,.035,.013);}
  function bombSpawn(){const a=Math.random()*Math.PI*2,rr=rnd(.12,.52);S.bomb={x:S.cx+Math.cos(a)*S.rx*rr,y:S.cy+Math.sin(a)*S.ry*rr,t:1.25,max:1.25,r:Math.min(110,S.ry*.36)};event('💣 폭탄 등장! 노란 위험 원에서 벗어나세요',1400);beep(360,.04,.012);}
  function bombBoom(){const b=S.bomb;if(!b)return;let n=0;for(const r of S.racers){if(!r.alive)continue;const dx=r.x-b.x,dy=r.y-b.y,d=Math.hypot(dx,dy)||1;if(d>b.r)continue;n++;const f=300+(1-d/b.r)*620;hit(r,dx/d,dy/d,f,true);}S.fx.push({type:'boom',x:b.x,y:b.y,r:b.r,age:0,ttl:.78});S.bomb=null;S.nextBomb=S.sudden?rnd(3.2,4.4):rnd(5.0,6.6);event(`💥 강폭발! ${n}명 크게 밀려남`,1300);beep(105,.09,.028);}
  function eliminate(r,e){if(!r.alive)return;r.alive=false;r.t=e;S.out.push(r);S.fx.push({type:'out',x:r.x,y:r.y,age:0,ttl:.7,text:'OUT!'});event(`💨 ${r.name} 링 아웃! · ${S.racers.filter(x=>x.alive).length}명 생존`);beep(115,.06,.021);}
  function begin(list){const{w,h}=resize(),cx=w/2,cy=h/2,rx=w*.465,ry=h*.43;S={cx,cy,startRX:rx,startRY:ry,rx,ry,out:[],fx:[],bomb:null,nextBomb:rnd(7,9),sudden:false,racers:list.map((name,i)=>{const a=i/list.length*Math.PI*2+rnd(-.18,.18),rr=rnd(.18,.44);return{id:i,name,c:color(name),x:cx+Math.cos(a)*rx*rr,y:cy+Math.sin(a)*ry*rr,vx:rnd(-70,70),vy:rnd(-70,70),r:Math.max(10,Math.min(14,14-list.length*.035)),alive:true,punch:rnd(.55,1.25),wind:0,target:null,flash:0,hit:0,blast:0,phase:Math.random()*10};})};running=true;last=started=performance.now();status.textContent='진행 중 · WIDE BOXING ARENA';event('🥊 난투 시작! 5초 후부터 링이 빠르게 좁아집니다',1900);updateRank();raf=requestAnimationFrame(loop);}
  function startBattle(){if(running||counting)return;const p=parse();if(p.out.length<2){pop('참가자를 2명 이상 입력하세요.');return;}const list=prepared?[...prepared]:mix([...p.out]);prepared=null;winner.classList.remove('show');winnerShown=false;results.innerHTML='';feed.innerHTML='';counting=true;lock(true);status.textContent='권투 배틀 준비 중';let n=3;countdown.textContent=n;countdown.classList.add('show');beep(560,.07,.03);const timer=setInterval(()=>{n--;if(n>0){countdown.textContent=n;beep(650+n*40,.06,.028);return;}clearInterval(timer);countdown.textContent='GO!';beep(900,.09,.04);setTimeout(()=>{countdown.classList.remove('show');countdown.textContent='';counting=false;begin(list);},340);},620);}
  function finish(){running=false;const rank=ranking(),top=rank[0];if(top){winnerName.textContent=top.name;winner.querySelector('small').textContent='LAST SURVIVOR';winner.classList.add('show');status.textContent=`완료 · 1등 ${top.name}`;beep(790,.12,.05);setTimeout(()=>beep(990,.12,.04),110);}progress.textContent='FINISH';lock(false);start.disabled=parse().out.length<2;start.textContent='AGAIN';updateRank();}
  function step(dt,now){const elapsed=(now-started)/1000;if(!S.sudden&&elapsed>28){S.sudden=true;event('🔥 SUDDEN DEATH! 링 축소와 펀치가 더 강해집니다',1700);beep(700,.08,.024);}const shrink=Math.min(1,Math.max(0,elapsed-5)/38);const loss=(S.sudden?.58:.40)*shrink;S.rx=S.startRX*(1-loss);S.ry=S.startRY*(1-loss);if(elapsed>43){const ex=Math.max(.64,1-(elapsed-43)*.026);S.rx*=ex;S.ry*=ex;}S.nextBomb-=dt;if(!S.bomb&&S.nextBomb<=0)bombSpawn();if(S.bomb){S.bomb.t-=dt;if(S.bomb.t<=0)bombBoom();}const alive=S.racers.filter(r=>r.alive);for(const r of alive){r.punch-=dt;r.flash=Math.max(0,r.flash-dt*4);r.hit=Math.max(0,r.hit-dt*4);r.blast=Math.max(0,r.blast-dt);if(r.wind>0){const prev=r.wind;r.wind-=dt;const t=S.racers.find(x=>x.id===r.target&&x.alive);if(t){const dx=t.x-r.x,dy=t.y-r.y,d=Math.hypot(dx,dy)||1;r.vx+=dx/d*28*dt;r.vy+=dy/d*28*dt;}if(prev>0&&r.wind<=0)punch(r);}else if(r.punch<=0){const n=nearest(r);if(n.t&&n.d<155){r.target=n.t.id;r.wind=.30;r.punch=S.sudden?rnd(.48,.78):rnd(.72,1.12);}else r.punch=rnd(.2,.45);}const dx=S.cx-r.x,dy=S.cy-r.y,d=Math.hypot(dx,dy)||1,norm=ell(r),inward=norm>.75?32:8;r.vx+=dx/d*inward*dt;r.vy+=dy/d*inward*dt;const tangent=Math.sin(elapsed*1.05+r.phase)*16;r.vx+=-dy/d*tangent*dt;r.vy+=dx/d*tangent*dt;const mover=nearest(r);if(mover.t&&r.blast<=0){const mx=mover.t.x-r.x,my=mover.t.y-r.y,md=Math.hypot(mx,my)||1,chase=S.sudden?145:105;r.vx+=mx/md*chase*dt;r.vy+=my/md*chase*dt;}const drag=r.blast>0?.998:.994;r.vx*=Math.pow(drag,dt*60);r.vy*=Math.pow(drag,dt*60);const v=Math.hypot(r.vx,r.vy),max=r.blast>0?900:(S.sudden?400:345);if(v>max){r.vx=r.vx/v*max;r.vy=r.vy/v*max;}r.x+=r.vx*dt;r.y+=r.vy*dt;}for(let i=0;i<alive.length;i++)for(let j=i+1;j<alive.length;j++){const a=alive[i],b=alive[j],dx=b.x-a.x,dy=b.y-a.y,rr=a.r+b.r,d2=dx*dx+dy*dy;if(d2<=.01||d2>=rr*rr)continue;const d=Math.sqrt(d2),nx=dx/d,ny=dy/d,ov=rr-d;a.x-=nx*ov/2;a.y-=ny*ov/2;b.x+=nx*ov/2;b.y+=ny*ov/2;const rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel<0){const imp=-rel*.38+7;a.vx-=imp*nx;a.vy-=imp*ny;b.vx+=imp*nx;b.vy+=imp*ny;}}for(const r of alive){if(ell(r)>1+r.r/Math.min(S.rx,S.ry))eliminate(r,elapsed);}for(const f of S.fx)f.age+=dt;S.fx=S.fx.filter(f=>f.age<f.ttl);const survivors=S.racers.filter(r=>r.alive);progress.textContent=`생존 ${survivors.length} / ${S.racers.length} · 링 ${Math.round(S.rx/S.startRX*100)}%`;updateRank();if(survivors.length<=1){finish();return;}if(elapsed>62){const rank=ranking();for(const r of rank.slice(1).filter(x=>x.alive))eliminate(r,elapsed);finish();}}
  function glove(x,y,a,ext=0,alpha=1){ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.globalAlpha=alpha;ctx.translate(ext,0);ctx.fillStyle='#ff5f57';ctx.strokeStyle='rgba(255,255,255,.78)';ctx.lineWidth=1.3;ctx.beginPath();ctx.roundRect(-2,-7,13,14,5);ctx.fill();ctx.stroke();ctx.fillStyle='#d7423d';ctx.fillRect(-7,-4,7,8);ctx.restore();}
  function background(w,h){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#182c3b');g.addColorStop(1,'#07131d');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.04;ctx.strokeStyle='#fff';for(let x=-h;x<w+h;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x-h,h);ctx.stroke();}ctx.globalAlpha=1;}
  function draw(){const r=board.getBoundingClientRect(),w=r.width,h=r.height;background(w,h);ctx.fillStyle='rgba(255,255,255,.025)';ctx.beginPath();ctx.ellipse(S.cx,S.cy,S.rx,S.ry,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=S.sudden?'#ff625d':'#45d483';ctx.lineWidth=5;ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.06)';ctx.lineWidth=1;for(const k of [.25,.5,.75]){ctx.beginPath();ctx.ellipse(S.cx,S.cy,S.rx*k,S.ry*k,0,0,Math.PI*2);ctx.stroke();}ctx.fillStyle='rgba(255,255,255,.45)';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillText(S.sudden?'SUDDEN DEATH':'WIDE BOXING ARENA',S.cx,S.cy+4);if(S.bomb){const b=S.bomb,pulse=.9+.1*Math.sin(performance.now()/75);ctx.fillStyle='rgba(255,70,65,.08)';ctx.strokeStyle='#ffca4b';ctx.lineWidth=3;ctx.beginPath();ctx.arc(b.x,b.y,b.r*pulse,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#171717';ctx.beginPath();ctx.arc(b.x,b.y,14,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffca4b';ctx.font='900 11px system-ui';ctx.fillText(`💣 ${Math.max(0,b.t).toFixed(1)}`,b.x,b.y-22);}for(const b of S.racers){if(!b.alive)continue;const t=S.racers.find(x=>x.id===b.target&&x.alive),a=t?Math.atan2(t.y-b.y,t.x-b.x):Math.atan2(b.vy,b.vx||1),wind=b.wind>0?1-b.wind/.30:0,ext=b.wind>0?4+wind*13:b.flash>0?18*b.flash:3,pa=a+Math.PI/2;glove(b.x+Math.cos(pa)*7,b.y+Math.sin(pa)*7,a,ext);glove(b.x-Math.cos(pa)*7,b.y-Math.sin(pa)*7,a,0,.78);if(b.wind>0&&t){ctx.strokeStyle='rgba(255,202,75,.45)';ctx.setLineDash([4,5]);ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(t.x,t.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#ffca4b';ctx.font='950 13px system-ui';ctx.fillText('!',b.x,b.y-b.r-16);}if(b.hit>0){ctx.strokeStyle=`rgba(255,235,120,${b.hit})`;ctx.lineWidth=3;ctx.beginPath();ctx.arc(b.x,b.y,b.r+9*(1-b.hit),0,Math.PI*2);ctx.stroke();}ctx.fillStyle=b.c;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.75)';ctx.lineWidth=1.2;ctx.stroke();ctx.fillStyle='#fff';ctx.font='800 9px system-ui';ctx.fillText(b.name,b.x,b.y+b.r+13);}for(const f of S.fx){const p=f.age/f.ttl,a=1-p;ctx.globalAlpha=a;if(f.type==='pow'||f.type==='out'){ctx.fillStyle=f.type==='pow'?'#ffef75':'#ff7069';ctx.font=`1000 ${18+8*p}px system-ui`;ctx.fillText(f.text,f.x,f.y-10*p);}else if(f.type==='boom'){ctx.strokeStyle='#ffca4b';ctx.lineWidth=5;ctx.beginPath();ctx.arc(f.x,f.y,f.r*(.2+.8*p),0,Math.PI*2);ctx.stroke();}ctx.globalAlpha=1;}}
  function loop(now){if(!running)return;const raw=Math.min((now-last)/1000,.035),dt=raw*(fastForward?3:1);last=now;step(dt,now);if(running){draw();raf=requestAnimationFrame(loop);}}
  multi.startSelected=()=>{if(multi.mode==='battle')startBattle();else originalStart();};
})();