(() => {
  const canvas=document.querySelector('#altGame'),board=document.querySelector('#board'),names=document.querySelector('#names'),status=document.querySelector('#status');if(!canvas||!board||!names||!status)return;
  const ctx=canvas.getContext('2d'),palette=['#ff6b62','#ffd166','#45d483','#5bbcff','#a78bfa','#ff8cc8','#74d7c4','#f59e0b','#7dd3fc','#fb7185'];let last=0;
  function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
  function parseNames(){const out=[];for(const raw of names.value.split(/[\n,]+/)){const s=raw.trim();if(!s)continue;const m=s.match(/^(.*?)(?:\*(\d+))?$/),name=(m?.[1]||s).trim(),w=Math.max(1,Math.min(8,Number(m?.[2]||1)));for(let i=0;i<w;i++)out.push(name);}return out.slice(0,24);}
  function resize(){const r=board.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(320,r.width),h=Math.max(440,r.height);canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(d,0,0,d,0,0);return{w,h};}
  function glove(x,y,a,ext=0,alpha=1){ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.globalAlpha=alpha;ctx.translate(ext,0);ctx.fillStyle='#ff5f57';ctx.strokeStyle='rgba(255,255,255,.78)';ctx.lineWidth=1.2;ctx.beginPath();ctx.roundRect(-2,-7,13,14,5);ctx.fill();ctx.stroke();ctx.fillStyle='#d7423d';ctx.fillRect(-7,-4,7,8);ctx.restore();}
  function draw(now){const{w,h}=resize(),list=parseNames(),cx=w/2,cy=h/2+8,rx=w*.42,ry=h*.37,p=1+Math.sin(now/850)*.012;const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#182c3b');g.addColorStop(1,'#07131d');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.04;ctx.strokeStyle='#fff';for(let x=-h;x<w+h;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x-h,h);ctx.stroke();}ctx.globalAlpha=1;ctx.fillStyle='rgba(255,255,255,.025)';ctx.beginPath();ctx.ellipse(cx,cy,rx*p,ry*p,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#45d483';ctx.lineWidth=5;ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.065)';ctx.lineWidth=1;for(const k of [.25,.5,.75]){ctx.beginPath();ctx.ellipse(cx,cy,rx*k,ry*k,0,0,Math.PI*2);ctx.stroke();}const ba=now/2900,bx=cx+Math.cos(ba)*rx*.42,by=cy+Math.sin(ba*.88)*ry*.36,br=Math.min(76,ry*.22)*(1+.05*Math.sin(now/100));ctx.fillStyle='rgba(255,70,65,.055)';ctx.strokeStyle='#ffca4b';ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(bx,by,br,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#171717';ctx.beginPath();ctx.arc(bx,by,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffca4b';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillText('💣',bx,by+4);list.forEach((name,i)=>{const base=i/list.length*Math.PI*2+(hash(name)%100)/350,orbit=base+Math.sin(now/1800+i*.73)*.08,lane=.25+((i*37)%55)/100,x=cx+Math.cos(orbit)*rx*lane,y=cy+Math.sin(orbit)*ry*lane,r=Math.max(10,Math.min(14,14-list.length*.05)),face=orbit+Math.PI/2+Math.sin(now/1200+i)*.45,perp=face+Math.PI/2;glove(x+Math.cos(perp)*7,y+Math.sin(perp)*7,face,4+Math.max(0,Math.sin(now/420+i*1.9))*5);glove(x-Math.cos(perp)*7,y-Math.sin(perp)*7,face,0,.72);ctx.fillStyle=palette[(hash(name)+i)%palette.length];ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.78)';ctx.lineWidth=1.2;ctx.stroke();ctx.fillStyle='#fff';ctx.font=`800 ${list.length>15?7:9}px system-ui`;ctx.fillText(name,x,y+r+13,64);});ctx.fillStyle='rgba(255,255,255,.18)';ctx.font='1000 58px system-ui';ctx.fillText('READY',cx,cy+18);ctx.fillStyle='rgba(255,255,255,.82)';ctx.font='950 23px system-ui';ctx.fillText('BOXING BATTLE ROYALE',cx,cy-20);ctx.fillStyle='rgba(255,255,255,.5)';ctx.font='650 11px system-ui';ctx.fillText(list.length?`${list.length}명 대기 중 · START를 누르면 동시에 난투 시작`:'참가자를 입력하면 링 안에 미리 표시됩니다',cx,cy+42);}
  function loop(now){if(window.SB365Multi?.mode==='battle'&&status.textContent.includes('대기 중')&&now-last>33){draw(now);last=now;}requestAnimationFrame(loop);}requestAnimationFrame(loop);
})();